name: Fetch Updates

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: 'Setup Dependencies'
        run: yarn
      - name: 'Update'
        run: yarn update
      - name: 'Print git status'
        run: git status
      - name: 'Print git diff'
        run: git diff
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: Update libraries
          branch: ${{ github.head_ref }}

          commit_user_name: TheSavior
          commit_user_email: github@eli-white.com
          commit_author: Eli White <github@eli-white.com>